# Generated by Django 3.1.7 on 2021-04-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='product1',
        ),
    ]
