# Generated by Django 3.1.7 on 2021-04-21 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210421_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='product2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('body', models.TextField()),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
