# Generated by Django 3.1.7 on 2021-05-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product2',
        ),
    ]
