# Generated by Django 3.1.7 on 2021-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210608_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
