# Generated by Django 3.1.7 on 2021-04-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketer',
            name='phone',
        ),
    ]
